---
on:
  pull_request:
  push:
    branches: [main]
    tags: ["*"]

jobs:
  rust_checks:
    name: Rust checks
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: setup rust toolchain
        uses: dtolnay/rust-toolchain@1.92
        with:
          components: clippy,rustfmt
      - run: cargo fmt --check
      - name: install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - run: cargo hack clippy --all-targets --feature-powerset --group-features hf,stt --no-deps -- -Dclippy::pedantic
      - run: cargo hack test --all-targets --feature-powerset --group-features hf,stt

  publish:
    needs: rust_checks
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          file: Containerfile
          push: true
          tags: |
            ghcr.io/heywillow/willow-inference-server-rs:${{ github.ref_name }}
            ${{ startsWith(github.ref, 'refs/tags/') && format('ghcr.io/heywillow/willow-inference-server-rs:latest') || '' }}
